
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150226 (SVN rev 63)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int MOD = 10;
  public static final int AND = 28;
  public static final int MULTIPLY = 9;
  public static final int ELSE = 24;
  public static final int NOTEQ = 15;
  public static final int OR = 27;
  public static final int THEN = 23;
  public static final int EQUAL = 16;
  public static final int WHILE = 25;
  public static final int CURLY_BRACKET_CLOSE = 5;
  public static final int RETURN = 21;
  public static final int IDENTIFIER = 11;
  public static final int GREATER = 17;
  public static final int FUNCTION = 20;
  public static final int BOOLEAN_FALSE = 32;
  public static final int IF = 22;
  public static final int PROGRAM = 19;
  public static final int DO = 26;
  public static final int CURLY_BRACKET_OPEN = 4;
  public static final int BOOLEAN_TRUE = 31;
  public static final int STRING = 30;
  public static final int FLOAT = 34;
  public static final int COMPARE = 12;
  public static final int EOF = 0;
  public static final int DIVIDE = 6;
  public static final int GREATEREQ = 14;
  public static final int ROUND_BRACKET_CLOSE = 3;
  public static final int ADD = 7;
  public static final int MINUS = 8;
  public static final int PRINT = 29;
  public static final int error = 1;
  public static final int LESSEQ = 13;
  public static final int INTEGER = 33;
  public static final int ROUND_BRACKET_OPEN = 2;
  public static final int LESS = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ROUND_BRACKET_OPEN",
  "ROUND_BRACKET_CLOSE",
  "CURLY_BRACKET_OPEN",
  "CURLY_BRACKET_CLOSE",
  "DIVIDE",
  "ADD",
  "MINUS",
  "MULTIPLY",
  "MOD",
  "IDENTIFIER",
  "COMPARE",
  "LESSEQ",
  "GREATEREQ",
  "NOTEQ",
  "EQUAL",
  "GREATER",
  "LESS",
  "PROGRAM",
  "FUNCTION",
  "RETURN",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "DO",
  "OR",
  "AND",
  "PRINT",
  "STRING",
  "BOOLEAN_TRUE",
  "BOOLEAN_FALSE",
  "INTEGER",
  "FLOAT"
  };
}

